alias c='clear'
alias h='history'
alias hg='history |grep -i '
alias edal='vi ~/.bash_aliases'
alias sb='. ~/.bashrc'
alias k='kubectl'
alias ping='ping -c 4'
alias locate='locate -i'

# find to skip /mnt folder on wsl.
function wfind() {
if [ -z "$1" ]; then
echo search argument required
return
else
        folders=("/dev" "/etc" "/home" "/media" "/opt" "/run" "/srv" "/tmp" "/usr" "/var")
        for f in ${folders[*]};do
                find $f -name $1
        done
fi
}
